
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Nov 28 18:05:42 CLT 2016
//----------------------------------------------------

package ejemplocup;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PENUP = 22;
  public static final int AND = 24;
  public static final int DIRECCION = 29;
  public static final int ELSE = 15;
  public static final int OR = 25;
  public static final int THEN = 14;
  public static final int PENCOL = 21;
  public static final int TABLECOL = 18;
  public static final int DIRDPEN = 11;
  public static final int SEMI = 2;
  public static final int WHILE = 16;
  public static final int NOT = 26;
  public static final int COLOR = 28;
  public static final int IF = 13;
  public static final int BOOLEANO = 30;
  public static final int OP_SUMA = 3;
  public static final int DO = 17;
  public static final int GOFWD = 12;
  public static final int PENDOWN = 23;
  public static final int PENDIR = 20;
  public static final int EOF = 0;
  public static final int BOUND = 19;
  public static final int COLORDPEN = 10;
  public static final int PARENIZQ = 6;
  public static final int error = 1;
  public static final int DOWNDPEN = 8;
  public static final int PARENDER = 7;
  public static final int OP_MULT = 5;
  public static final int ENTERO = 27;
  public static final int UPDPEN = 9;
  public static final int OP_RESTA = 4;
}

